### ISSUE TITLE
Can sort resources by group?

### ISSUE THREAD

**Issue by klarkxy** [brevven/bzvery#1]
![image](https://user-images.githubusercontent.com/6316992/230768785-b68c1ff3-6fbb-48bb-8c47-a44521f83bf4.png)
The se-core-fragments and raw-resources (in the red rectangle) are in a mixed subgroup, doesnot in it's own subgroup.
Can sort it like SE does (in the green rectangle)?

**Comment by brevven** [comment]
Thanks, will fix this over the coming weeks. I will track in a centralized issue board: https://github.com/brevven/bz/issues/68
